[build]
  publish = "."
  
[[redirects]]
  from = "/"
  to = "/bijou-story-v2.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"